### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by a-dams154** [mikebevz/node-imap#6]
Error: Timed out while authenticating with server
    at Timeout._onTimeout (C:\Users\Tony George\WEBRTC\SourceCode\nowdigital_backend\node_modules\node-imap\lib\Connection.js:139:21)
    at listOnTimeout (internal/timers.js:554:17)       
    at processTimers (internal/timers.js:497:7) {      
  source: 'timeout-auth'
}

**Comment by arnt** [comment]
Hi,

do you mean that node-imap does something wrong and causes a timeout, or are you reporting a network/server timeout as a bug in node-imap? In the former case, more detail is needed.

**Comment by arnt** [comment]
I'll close this now since I can't reproduce it and it's 2½ years old.

**Comment by arnt** [comment]
Oh, oops, wrong close reason. Fixed now.
