### ISSUE TITLE
Crash on failed network?

### ISSUE THREAD

**Issue by friesendrywall** [mikebevz/node-imap#7]
On my dev machine, I've caught this crash, any thoughts what this would take to fix?  Node version 14.15.4

```
buffer.js:333
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null
    at Function.from (buffer.js:333:9)
    at Parser.parseFetch (C:\Aercon Software\aerworxV2\api\node_modules\node-imap\lib\Parser.js:448:20)
    at Parser._resUntagged (C:\Aercon Software\aerworxV2\api\node_modules\node-imap\lib\Parser.js:258:26)
    at Parser._parse (C:\Aercon Software\aerworxV2\api\node_modules\node-imap\lib\Parser.js:133:18)
    at Parser._tryread (C:\Aercon Software\aerworxV2\api\node_modules\node-imap\lib\Parser.js:77:17)
    at TLSSocket.Parser._cbReadable (C:\Aercon Software\aerworxV2\api\node_modules\node-imap\lib\Parser.js:55:14)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitReadable_ (internal/streams/readable.js:569:12)
    at processTicksAndRejections (internal/process/task_queues.js:79:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by arnt** [comment]
Hi,

I had a look, and…

It's possible for a single part in a multipart message to be absolutely empty. Zero bytes long. (A singlepart message has to contain at least a CRLF.) When that happens, most IMAP servers will send it to clients as an empty string and a few as a `NIL`. It seems as if node-imap isn't robust against the latter.

**Comment by arnt** [comment]
I'll close this now since I can't reproduce it. I can guess what happens, but guesswork is no substitute for reproduction.

If you (still use node-imap and) can send an IMAP command/response log I'll be happy to turn your log into a unit test and then make the test pass.
